language: generic
dist: bionic
global:
  - CLIVERSION=0.7.2
  
before_install:
  - mkdir -p "$HOME/bin"
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/bin" sh
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - arduino-cli  core install Seeeduino:samd --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - |
    installLibrary() {
      local -r repositoryFullName="$1"
      local -r repositoryName="${repositoryFullName##*/}"
      # clone repository to the libraries folder of the sketchbook
      git clone https://github.com/${repositoryFullName} "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${TRAVIS_BUILD_DIR}"
    }
  - installLibrary Seeed-Studio/Seeed_Arduino_FreeRTOS
  - installLibrary Seeed-Studio/Seeed_Arduino_ooFreeRTOS
  - installLibrary Seeed-Studio/Seeed_Arduino_LIS3DHTR
  - installLibrary Seeed-Studio/Seeed_Arduino_MultiGas
  - installLibrary Seeed-Studio/Seeed_Arduino_SFUD
  - installLibrary Seeed-Studio/Grove_BME280
  - installLibrary Seeed-Studio/Seeed_Arduino_DPS310
  - installLibrary Seeed-Studio/Seeed_Arduino_TFlidar
  - installLibrary Seeed-Studio/Grove_6Axis_Accelerometer_And_Gyroscope_BMI088
  - installLibrary Seeed-Studio/Seeed_Arduino_UltrasonicRanger
  - installLibrary Seeed-Studio/Seeed_SCD30
  - cd ${HOME}/Arduino/libraries/
  - git clone https://github.com/Seeed-Studio/Seeed_Arduino_mbedtls -b edge-impulse
  - cd ${HOME}/Arduino/libraries/Seeed_Arduino_mbedtls
  - cd "${TRAVIS_BUILD_DIR}"
  - git clone https://github.com/Seeed-Studio/Seeed_Arduino_edgeimpulse 
  
install:
  - cd Seeed_Arduino_edgeimpulse  

script:
  - ls
  - ./arduino-build.sh --build

notifications:
  email:
    on_success: change
    on_failure: change