language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
  - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-simple-ci.sh

script:
   - chmod +x seeed-arduino-simple-ci.sh
   - cat $PWD/seeed-arduino-simple-ci.sh
   - bash $PWD/seeed-arduino-simple-ci.sh -b "Seeeduino:samd:seeed_wio_terminal" -s listfiles/ReadWrite/SD_Test

notifications:
  email:
    on_success: change
    on_failure: change